name: Update Languages Card
permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *"   
  workflow_dispatch:        

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate languages card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: assets/languages.svg

          base: ""
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 12
          plugin_languages_threshold: 0%
          
          config_display: regular
          config_padding: 16
          config_timezone: Europe/Stockholm

      - name: Commit and push
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add assets/languages.svg
          git commit -m "Update languages.svg" || echo "No changes"
          git push
