name: Update languages card

on:
  schedule:
    - cron: "0 3 * * *"   
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate languages card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          filename: assets/languages.svg

          base: ""

          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_ignored: ""
          plugin_languages_threshold: 0%
          plugin_languages_colors: github

          # Tema / färger – mörkt + lila vibe
          config_timezone: Europe/Stockholm
          config_padding: 16, 20, 16, 20
          config_display: regular
          config_border: 10
          config_animations: yes
          config_background: "000000"
          config_theme: "nightowl"
